/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { CanvasAddNodeRequest, CanvasLinkRequest, CanvasSaveAssetRequest, CanvasSaveAssetValue, CanvasState, CanvasUpdateNodeRequest } from '@ldd/dsh-canvas/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$63616e766173 {
    addNode: (sessionId: SessionId, request: CanvasAddNodeRequest) => Promise<RemoteResult<CanvasState>>
    inspect: (sessionId: SessionId) => Promise<RemoteResult<CanvasState>>
    link: (sessionId: SessionId, request: CanvasLinkRequest) => Promise<RemoteResult<CanvasState>>
    moveNode: (sessionId: SessionId, nodeId: string, x: number, y: number) => Promise<RemoteResult<CanvasState>>
    removeNode: (sessionId: SessionId, nodeId: string) => Promise<RemoteResult<CanvasState>>
    saveAsset: (sessionId: SessionId, request: CanvasSaveAssetRequest) => Promise<RemoteResult<CanvasSaveAssetValue>>
    updateNode: (sessionId: SessionId, nodeId: string, patch: CanvasUpdateNodeRequest) => Promise<RemoteResult<CanvasState>>
  }
  interface TypertRemoteMap {
    'canvas/addNode': (sessionId: SessionId, request: CanvasAddNodeRequest) => Promise<RemoteResult<CanvasState>>
    'canvas/inspect': (sessionId: SessionId) => Promise<RemoteResult<CanvasState>>
    'canvas/link': (sessionId: SessionId, request: CanvasLinkRequest) => Promise<RemoteResult<CanvasState>>
    'canvas/moveNode': (sessionId: SessionId, nodeId: string, x: number, y: number) => Promise<RemoteResult<CanvasState>>
    'canvas/removeNode': (sessionId: SessionId, nodeId: string) => Promise<RemoteResult<CanvasState>>
    'canvas/saveAsset': (sessionId: SessionId, request: CanvasSaveAssetRequest) => Promise<RemoteResult<CanvasSaveAssetValue>>
    'canvas/updateNode': (sessionId: SessionId, nodeId: string, patch: CanvasUpdateNodeRequest) => Promise<RemoteResult<CanvasState>>
  }
  interface TypertRemoteNamespaceMap {
    'canvas': TypertRemoteNamespace$63616e766173
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
